name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # IMPORTANT: needed to retain history

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask/requirements.txt
        pip install allure-pytest

    - name: Run tests and generate Allure report
      run: |
        pytest --alluredir=allure-results
        mkdir -p allure-history
        if [ -d "allure-report" ]; then cp -r allure-report/history allure-history/; fi
        allure generate allure-results -o allure-report --clean
        cp -r allure-history allure-report/history || true

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report
        keep_files: true
