name: Run Tests and Publish Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Pytest with Allure and Deploy Report
    runs-on: ubuntu-latest

    steps:
      ### 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      ### 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      ### 3. Install dependencies
      - name: Install Python dependencies
        run: |
          pip install -r Flask/requirements.txt
          pip install pytest allure-pytest

      ### 4. Install Allure CLI
      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.27.0/bin/allure /usr/local/bin/
          allure --version

      ### 5. Run tests with Allure results
      - name: Run pytest
        continue-on-error: true
        run: |
          mkdir -p Flask/allure-results
          pytest Flask/ --alluredir=Flask/allure-results || true

      ### 6. Download previous history
      - name: Download previous Allure history artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: Flask/allure-results/history

      ### 7. Generate Allure report (with injected history)
      - name: Generate Allure report
        run: |
          allure generate Flask/allure-results --clean -o Flask/allure-report

      ### 8. Save new history for next run
      - name: Upload updated Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: Flask/allure-report/history

      ### 9. Deploy report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./Flask/allure-report
          publish_branch: gh-pages
          force_orphan: true
