name: Run tests and publish Allure report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Flask/requirements.txt
          pip install allure-pytest

      - name: Create allure-results folder
        run: mkdir -p ./Flask/allure-results

      - name: Try to download previous Allure report
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: allure-full-report
          path: ./Flask

      - name: Extract previous history if available
        run: |
          mkdir -p ./Flask/allure-report ./Flask/allure-results/history
          if [ -f ./Flask/allure-full-report.tar.gz ]; then
            echo "Extracting previous history"
            tar -xzf ./Flask/allure-full-report.tar.gz -C ./Flask
            cp -r ./Flask/allure-report/history/* ./Flask/allure-results/history/ || echo "No history folder inside archive"
          else
            echo "No previous report archive found (likely first run)"
          fi

      - name: Run tests with Allure
        run: |
          pytest Flask/tests --alluredir=Flask/allure-results
        env:
          RENDER_SQL: ${{ secrets.RENDER_SQL }}

      - name: Generate Allure report
        run: |
          allure generate ./Flask/allure-results --clean -o ./Flask/allure-report

      - name: Package Allure report (incl. history)
        run: tar -czf allure-full-report.tar.gz -C ./Flask allure-report

      - name: Upload Allure report artifact for next run
        uses: actions/upload-artifact@v4
        with:
          name: allure-full-report
          path: allure-full-report.tar.gz

      - name: Deploy Allure report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Flask/allure-report
          publish_branch: gh-pages
          force_orphan: true
