name: Run Pytest and Deploy Allure Report

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Flask/requirements.txt
        pip install allure-pytest

    # Download previous report (contains history)
    - name: Download previous Allure report
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: prev-report
      continue-on-error: true

    # Clean old results
    - name: Remove old results and prepare new one
      run: |
        rm -rf Flask/allure-results
        mkdir -p Flask/allure-results

    # Run tests and collect new results
    - name: Run tests and store new results
      run: |
        pytest Flask/ --alluredir=Flask/allure-results

    # Inject previous history into current results
    - name: Inject previous history into new results
      run: |
        if [ -d "prev-report/history" ]; then
          mkdir -p Flask/allure-results/history
          cp -r prev-report/history/* Flask/allure-results/history/
        else
          echo "No previous history found"
        fi

    # Install Allure CLI
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        allure --version

    # Generate final report
    - name: Generate Allure report
      run: |
        allure generate Flask/allure-results --clean -o Flask/allure-report

    # Upload full new report for history reuse
    - name: Upload Allure report (with history)
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: Flask/allure-report

    # Deploy to GitHub Pages
    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./Flask/allure-report
        publish_branch: gh-pages
        force_orphan: true
