name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ./Flask
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre-headless
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Download previous Allure history
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: ./Flask/prev-history

    - name: Run tests and generate Allure report (even on failure)
      working-directory: ./Flask
      run: |
        # Run tests, always continue
        pytest --alluredir=allure-results || echo "Tests failed but continuing..."

        mkdir -p allure-results/history
        cp -r ./prev-history/* allure-results/history || echo "No previous history"
        allure generate allure-results -o allure-report --clean

    - name: Upload Allure history
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: ./Flask/allure-report/history

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: ./Flask/allure-report
        keep_files: true
