name: Run tests and publish Allure report with history

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r Flask/requirements.txt
        pip install allure-pytest

    - name: download allure-history from gh-pages
      run: |
        # Ensure we start on main (or your default branch)
        git checkout main

        # Create directory to store copied history
        mkdir -p prev/history

        # Fetch the gh-pages branch
        git fetch origin gh-pages --depth=1

        # Create a temporary directory to check out gh-pages contents
        mkdir gh-temp
        cd gh-temp

        # Check out just the gh-pages branch contents (sparse checkout to avoid mixing branches)
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin gh-pages --depth=1
        git checkout origin/gh-pages

        # Copy the history folder if it exists
        if [ -d "history" ]; then
          cp -r history ../prev/history/
          echo "✅ Copied history to prev/history"
        else
          echo "⚠️ No history directory found in gh-pages"
        fi

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        allure --version

    - name: Run tests and generate new allure-results
      continue-on-error: true
      run: |
        pytest Flask/ --alluredir=Flask/allure-results

    - name: Inject previous history into new allure-results
      run: |
        
        cd prev/history/history
        ls
        
        # Copy previous history if exists
        if [ -d "prev/history/history" ]; then
          cp -r prev/history/history Flask/allure-results/history/
          echo "✅ Previous history copied"
        else
          echo "⚠️ No history directory found in gh-pages"
        fi
      
    - name: Generate allure report with history
      run: |
        allure generate Flask/allure-results --clean -o Flask/allure-report

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./Flask/allure-report
        publish_branch: gh-pages
        force_orphan: true
