name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ./Flask
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre-headless
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Run tests and generate Allure report
      working-directory: ./Flask
      continue-on-error: true
      run: |
        pytest --alluredir=allure-results

        # Download previous report history from gh-pages
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch origin gh-pages --depth=1
        git checkout gh-pages || git checkout -b gh-pages
        mkdir -p ../prev-history
        cp -r ./allure-report/history ../prev-history || echo "No previous history"

        # Go back to main branch for report generation
        git checkout -

        # Restore previous history into results
        mkdir -p allure-results/history
        cp -r ../prev-history/* allure-results/history || echo "No history to restore"

        # Generate new report including history
        allure generate allure-results -o allure-report --clean


    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: ./Flask/allure-report
        keep_files: true
