name: Run tests and publish Allure report with history

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r Flask/requirements.txt
        pip install allure-pytest

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        allure --version

    - name: Run tests and generate new allure-results
      continue-on-error: true
      run: |
        pytest Flask/ --alluredir=Flask/allure-results

    - name: Inject previous history into new allure-results
      run: |
        
        # Fetch gh-pages branch shallowly to reduce data
        git fetch origin gh-pages --depth=1

        git checkout gh-pages

        # Copy previous history if exists
        if [ -d "history" ]; then
          cp -r history Flask/allure-results/history/
          echo "✅ Previous history copied"
        else
          echo "⚠️ No history directory found in gh-pages"
        fi

        # Go back to main
        git checkout -
      
    - name: Generate allure report with history
      run: |
        allure generate Flask/allure-results 
        # --clean -o Flask/allure-report

    - name: Deploy allure report to gh-pages branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout gh-pages || git checkout --orphan gh-pages
        # Clear old report
        rm -rf *
        # Copy new report and history
        cp -r Flask/allure-report/* .
        touch .nojekyll
        git add .
        git commit -m "Update Allure report with history"
        git push origin gh-pages --force
