name: Run Tests and Publish Allure Report

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Flask/requirements.txt

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xvzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Download previous report history (if exists)
      uses: actions/download-artifact@v4
      with:
        name: allure-full-report
        path: Flask/prev-history
      continue-on-error: true

    - name: Run pytest with Allure
      run: |
        pytest Flask/ --alluredir=Flask/allure-results
      continue-on-error: true  # allow test failure but keep workflow running

    - name: Restore previous history into results
      run: |
        mkdir -p Flask/allure-results/history
        cp -r Flask/prev-history/history/* Flask/allure-results/history/ || true

    - name: Generate Allure Report
      run: |
        allure generate Flask/allure-results --clean -o Flask/allure-report

    - name: Upload Allure Report Artifact (with history)
      uses: actions/upload-artifact@v4
      with:
        name: allure-full-report
        path: Flask/allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: Flask/allure-report
        publish_branch: gh-pages
