name: Run Postman tests with Newman on Node.js CI

on:
#  push:
#    paths:
#      - 'Flask/**'
#      - '!Flask/readme.md'
#  pull_request:
#    paths:
#      - 'Flask/**'
#      - '!Flask/readme.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm install -g newman
